//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ForcedCameraRotation : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Walking
        {
            get
            {
                return SteamVR_Actions.forcedCameraRotation_Walking;
            }
        }
        
        public virtual SteamVR_Action_Boolean CameraRotateLeft
        {
            get
            {
                return SteamVR_Actions.forcedCameraRotation_CameraRotateLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean CameraRotateRight
        {
            get
            {
                return SteamVR_Actions.forcedCameraRotation_CameraRotateRight;
            }
        }
    }
}
